version: "3"

services:
  model-server:
    image: tensorflow/serving:1.12.0
    volumes:
      - ./model:/models/q_and_a
    environment:
      - MODEL_NAME=q_and_a
    logging:
      driver: "json-file"
      options:
        max-size: "1k"
        max-file: "3"

  query-server:
    build:
      context: ./query_server/
      dockerfile: ./Dockerfile
    volumes:
      - ./model:/Users/makoto/work/dataset
      - ./my_problem:/Users/makoto/work/problem
    links:
      - model-server:model
    ports:
      - "5000:5000"
    command: bash -c "t2t-query-server --server=model:8500 --servable_name=q_and_a --problem=my_problem --data_dir=/Users/makoto/work/dataset --t2t_usr_dir=/Users/makoto/work/problem"
    logging:
      driver: "json-file"
      options:
        max-size: "1k"
        max-file: "3"
